/**
 * Curated Material Symbols ligature names for the icon picker — commerce/marketing glyphs
 * already common across this theme's default settings (docs/... icon-bar, icon-with-content,
 * shipping-checkpoints, announcement, etc.), rendered via the shared `.material-symbols-outlined`
 * ligature font (no icon library dependency).
 */
export const MATERIAL_SYMBOLS_ICONS: string[] = [
  // Commerce actions
  "shopping_cart",
  "shopping_bag",
  "add_shopping_cart",
  "storefront",
  "sell",
  "local_offer",
  "local_mall",
  "redeem",
  "discount",
  "loyalty",
  "receipt_long",
  "point_of_sale",
  "inventory",
  "category",
  "style",

  // Shipping & fulfillment
  "local_shipping",
  "inventory_2",
  "package_2",
  "conveyor_belt",
  "schedule_send",
  "public",
  "flight_takeoff",
  "location_on",
  "map",
  "track_changes",
  "undo",
  "autorenew",
  "replay",
  "restart_alt",

  // Trust & payment
  "verified",
  "verified_user",
  "shield",
  "gpp_good",
  "lock",
  "lock_open",
  "credit_card",
  "account_balance_wallet",
  "payments",
  "policy",
  "privacy_tip",
  "receipt",
  "handshake",
  "workspace_premium",
  "military_tech",

  // Social & ratings
  "star",
  "star_half",
  "star_border",
  "star_rate",
  "grade",
  "thumb_up",
  "thumb_up_alt",
  "favorite",
  "favorite_border",
  "share",
  "forum",
  "chat_bubble",
  "reviews",
  "sentiment_satisfied",
  "emoji_events",

  // Contact
  "call",
  "mail",
  "chat",
  "support_agent",
  "headset_mic",
  "schedule",
  "event",
  "calendar_month",
  "language",
  "person",
  "group",

  // Sustainability
  "eco",
  "recycling",
  "compost",
  "park",
  "water_drop",
  "spa",

  // General UI
  "check_circle",
  "check",
  "cancel",
  "close",
  "info",
  "help",
  "add",
  "add_circle",
  "remove",
  "search",
  "menu",
  "home",
  "arrow_forward",
  "arrow_back",
  "chevron_left",
  "chevron_right",
  "expand_more",
  "expand_less",
  "content_copy",
  "link",
  "download",
  "upload",
  "visibility",
  "visibility_off",
  "settings",
  "tune",
  "filter_list",
  "bolt",
  "flash_on",
  "new_releases",
  "celebration",
  "card_giftcard",
];
